/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String _kFontPkg = null;

  static const IconData telescope = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space_rover_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData international_space_station = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atronaut = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData space_shuttle = IconData(0xf197, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
